### ISSUE TITLE
First stand-alone version of oemof.tools v0.4.0

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof-tools#4]
As we decided to create separate packages we had to create a tool repository. This repository contains tools that can be used by any oemof package.

Now it is possible to use this little helper functions without installing a big oemof package but by installing the small oemof.tools package.

Even though the documentation still needs a revision the package itself and the basic documentation is fine. So we will release v0.4.0 at 2020-05-11.

**Comment by uvchik** [comment]
I copied the authors of the transferred files from the old repository.

**Comment by p-snft** [comment]
This seems to be done: https://pypi.org/project/oemof.tools/0.4.0/
