### ISSUE TITLE
oemof.tools installed but not usable

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-tools#5]
According to https://github.com/oemof/oemof-examples/issues/69, importing oemof.tools as follows
```Python
from oemof.tools import logger
```
may result in the following error message:
```
cannot import name 'logger' from 'oemof.tools' (unknown location)
```

**Comment by p-snft** [comment]
I have the feeling that it might be due to the fact that the `__init__.py`  is empty.

**Comment by uvchik** [comment]
I cannot reproduce this bug.

![grafik](https://user-images.githubusercontent.com/4760584/108119832-a3326800-70a0-11eb-8921-f3ff2d813264.png)

No error.

**Comment by uvchik** [comment]
@p-snft Do you have an old `oemof` installation?

**Comment by p-snft** [comment]
I can also not reproduce on my local computer. But I know that there are Python installations that have problems like this. (Anaconda on Windows?) It happens when you import from a file and can be solved by naming the possible imports in the init.
